networks: 
  yapi-mongo:
services: 
  mongodb: 
    container_name: mongo
    restart: always
    environment: 
      MONGO_INITDB_DATABASE: yapi
    image: "mongo:latest"
    networks: 
      - yapi-mongo
    ports: 
      - "27018:27017"
    volumes: 
      - "/home/yixiong/mongo/etc:/etc/mongo"
      - "/home/yixiong/mongo/data/db:/data/db"
  yapi: 
    build: ./
    restart: always
    container_name: yapi
    depends_on: 
      - mongodb
    image: yapi
    networks: 
      - yapi-mongo
    ports: 
      - "3621:3621"
    command: >
      /bin/bash -c '
      while ! nc -z mongodb 27017;
      do
        echo "wait for mongodb";
        sleep 1;
      done;
      echo "mongodb is ready!";
      cd /docker-yapi/yapi/vendors && if [ -d node_modules ]; then node server/app.js; else npm run install-server && node server/app.js; fi'